name: 'Basic'

on:
  push:
    branches:
    - main

jobs:
  build-test:
    name: 'First Job'

    strategy:
      matrix:
        os: [ 'windows-latest', 'macos-latest', 'ubuntu-latest' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Say Hello from OS - ${{ matrix.os}}
      shell: bash
      run: |
        echo :"Hello World from ${{ matrix.os}}"